-- 1. Create a table to store User Profiles
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text
);

-- 2. Create a table to store Generated Study Plans (History)
create table public.study_plans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  input_text text, -- Text summary of resume or skills
  language text,
  ai_response jsonb -- Stores the full AI result
);

-- 3. Enable Security (RLS)
alter table public.profiles enable row level security;
alter table public.study_plans enable row level security;

-- 4. Create Security Policies (Users can only see THEIR own data)
create policy "Users can view their own profile" 
on public.profiles for select using ( auth.uid() = id );

create policy "Users can update their own profile" 
on public.profiles for update using ( auth.uid() = id );

create policy "Users can view their own study plans" 
on public.study_plans for select using ( auth.uid() = user_id );

create policy "Users can save their study plans" 
on public.study_plans for insert with check ( auth.uid() = user_id );

-- 5. Auto-create profile when a new user signs up
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
